export default [
  {
    id: 1,
    title: 'Family Loaf',
    sub_title: 'Thai Style Red Curry, Crusty Bread',
    colories: '105 calories',
    price: 500,
    image_path: './bread1.jpg',
    category: 'bread',
    available: false,
  },
  {
    id: 2,
    title: 'Unslice Family Loaf',
    sub_title: 'amala and ewedu',
    colories: '109 calories',
    price: 800,
    image_path: './bread2.jpg',
    category: 'bread',
    available: true,
  },
  {
    id: 3,
    title: 'Bread Roll',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 12000,
    image_path: './bread3.jpg',
    category: 'bread',
    available: true,
  },
  {
    id: 4,
    title: 'Golden Bread',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 1000,
    image_path: './bread4.jpg',
    category: 'bread',
    available: true,
  },
  {
    id: 5,
    title: 'Tuiti Fruiti',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 2000,
    image_path: './menuimage4.png',
    category: 'bread',
    available: false,
  },
  {
    id: 6,
    title: 'Coconut super Bread',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 400,
    image_path: './menuimage4.png',
    category: 'bread',
    available: true,
  },
  {
    id: 7,
    title: 'Eba and Okra Soup',
    sub_title: 'spicy chicken red BBQ',
    colories: '105 calories',
    price: 8000,
    image_path: './menuimage1.png',
    category: 'swallow',
    available: true,
  },
  {
    id: 8,
    title: 'Amala with gbegiri',
    sub_title: 'amala and ewedu',
    colories: '109 calories',
    price: 3000,
    image_path: './menuimage2.png',
    category: 'swallow',
    available: true,
  },
  {
    id: 9,
    title: 'Fufu and Egusi',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 9000,
    image_path: './menuimage3.png',
    category: 'swallow',
    available: false,
  },
  {
    id: 10,
    title: 'Semo and Eforriro',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 12000,
    image_path: './menuimage3.png',
    category: 'swallow',
    available: false,
  },
  {
    id: 11,
    title: 'Jamboree Coconut',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 7000,
    image_path: './menuimage4.png',
    category: 'meals',
    available: true,
  },
  {
    id: 12,
    title: 'Leafy Beans',
    sub_title: 'spicy chicken red BBQ',
    colories: '105 calories',
    price: 4000,
    image_path: './menuimage1.png',
    category: 'meals',
    available: true,
  },
  {
    id: 13,
    title: 'Jollof Rice',
    sub_title: 'amala and ewedu',
    colories: '109 calories',
    price: 2000,
    image_path: './menuimage2.png',
    category: 'meals',
    available: true,
  },
  {
    id: 14,
    title: 'Fried Rice',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 1200,
    image_path: './menuimage3.png',
    category: 'meals',
    available: false,
  },
  {
    id: 15,
    title: 'Spagetti',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 1700,
    image_path: './menuimage4.png',
    category: 'meals',
    available: true,
  },
];
