export default [
  {
    title: 'Family Loaf',
    sub_title: 'Thai Style Red Curry, Crusty Bread',
    colories: '105 calories',
    price: 500,
    image_path: './menuimage1.png',
    category: 'bread',
    available: false,
  },
  {
    title: 'Unslice Family Loaf',
    sub_title: 'amala and ewedu',
    colories: '109 calories',
    price: 800,
    image_path: './menuimage2.png',
    category: 'bread',
    available: true,
  },
  {
    title: 'Bread Roll',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 12000,
    image_path: './menuimage3.png',
    category: 'bread',
    available: true,
  },
  {
    title: 'Golden Chocolate Bread',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 1000,
    image_path: './menuimage4.png',
    category: 'bread',
    available: true,
  },
  {
    title: 'Tuiti Fruiti',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 2000,
    image_path: './menuimage4.png',
    category: 'bread',
    available: false,
  },
  {
    title: 'Coconut super Bread',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 400,
    image_path: './menuimage4.png',
    category: 'bread',
    available: true,
  },
  {
    title: 'Eba and Okra Soup',
    sub_title: 'spicy chicken red BBQ',
    colories: '105 calories',
    price: 8000,
    image_path: './menuimage1.png',
    category: 'swallow',
    available: true,
  },
  {
    title: 'Amala with gbegiri and efo',
    sub_title: 'amala and ewedu',
    colories: '109 calories',
    price: 3000,
    image_path: './menuimage2.png',
    category: 'swallow',
    available: true,
  },
  {
    title: 'Fufu and Egusi',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 9000,
    image_path: './menuimage3.png',
    category: 'swallow',
    available: false,
  },
  {
    title: 'Semo and Eforriro',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 12000,
    image_path: './menuimage3.png',
    category: 'swallow',
    available: false,
  },
  {
    title: 'Jamboree Coconut',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 7000,
    image_path: './menuimage4.png',
    category: 'meals',
    available: true,
  },
  {
    title: 'Leafy Beans',
    sub_title: 'spicy chicken red BBQ',
    colories: '105 calories',
    price: 4000,
    image_path: './menuimage1.png',
    category: 'meals',
    available: true,
  },
  {
    title: 'Jollof Rice',
    sub_title: 'amala and ewedu',
    colories: '109 calories',
    price: 2000,
    image_path: './menuimage2.png',
    category: 'meals',
    available: true,
  },
  {
    title: 'Fried Rice',
    sub_title: 'spicy chicken red BBQ',
    colories: '116 calories',
    price: 1200,
    image_path: './menuimage3.png',
    category: 'meals',
    available: false,
  },
  {
    title: 'Spagetti',
    sub_title: 'ukwobi prepared',
    colories: '98 calories',
    price: 1700,
    image_path: './menuimage4.png',
    category: 'meals',
    available: true,
  },
];
