export const ON_ORDER_SUCCESS = 'ON_ORDER_SUCCESS';
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS';
export const GET_USER_ORDERS_ERROR = 'GET_USER_ORDERS_ERROR';
export const ON_ORDER_ERROR = 'ON_ORDER_ERROR';
export const EMPTY_ORDER = 'EMPTY_ORDER';
